### ISSUE TITLE
How to send DeliverSmID to smpp client ??

### ISSUE THREAD

**Issue by vanipolnedi** [ajankovic/smpp#2]
Hi,
I'm able to send submitsm to connected clients. 
How to send DeliverSmID to smpp client ??

Thanks in advance.

**Comment by ajankovic** [comment]
If you have binded session you can send it same as any other PDU. There is also a helper to get proper type in response:

```
resp, err := smpp.SendDeliverSm(ctx, sess, p *pdu.DeliverSm)
```

**Comment by vanipolnedi** [comment]
@ajankovic  how can i access current sess for sending deliversm (resp, err := smpp.SendDeliverSm(ctx, **sess**, p *pdu.DeliverSm))
