### ISSUE TITLE
Is smpp.Session concurrency safe?

### ISSUE THREAD

**Issue by shashankmehra** [ajankovic/smpp#4]
The Send() function acquires a mutex lock when called and releases the lock when it is done with the smpp session. So it appears to be concurrency safe. Can you help me confirm that multiple goroutines can call Send() function concurrently without any issues?

Go libraries are assumed to not be concurrency-safe unless the documentation mentions otherwise. It would be helpful if concurrency safety is mentioned somewhere.

**Comment by ajankovic** [comment]
Yes, `session.Send()` is safe for concurrent usage. I'll update configuration.
